
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed2;

	private global::Gtk.Entry edtNome;

	private global::Gtk.Label lblNome;

	private global::Gtk.Button btnCliqueMe;

	private global::Gtk.Label lblViewNome;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed2 = new global::Gtk.Fixed();
		this.fixed2.Name = "fixed2";
		this.fixed2.HasWindow = false;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.edtNome = new global::Gtk.Entry();
		this.edtNome.CanFocus = true;
		this.edtNome.Name = "edtNome";
		this.edtNome.IsEditable = true;
		this.edtNome.InvisibleChar = '●';
		this.fixed2.Add(this.edtNome);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.edtNome]));
		w1.X = 112;
		w1.Y = 22;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.lblNome = new global::Gtk.Label();
		this.lblNome.Name = "lblNome";
		this.lblNome.LabelProp = global::Mono.Unix.Catalog.GetString("Nome: ");
		this.fixed2.Add(this.lblNome);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.lblNome]));
		w2.X = 67;
		w2.Y = 27;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.btnCliqueMe = new global::Gtk.Button();
		this.btnCliqueMe.CanFocus = true;
		this.btnCliqueMe.Name = "btnCliqueMe";
		this.btnCliqueMe.UseUnderline = true;
		this.btnCliqueMe.Label = global::Mono.Unix.Catalog.GetString("Clique ME");
		this.fixed2.Add(this.btnCliqueMe);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.btnCliqueMe]));
		w3.X = 201;
		w3.Y = 54;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.lblViewNome = new global::Gtk.Label();
		this.lblViewNome.Name = "lblViewNome";
		this.fixed2.Add(this.lblViewNome);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.lblViewNome]));
		w4.X = 67;
		w4.Y = 94;
		this.Add(this.fixed2);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 624;
		this.DefaultHeight = 304;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.btnCliqueMe.Clicked += new global::System.EventHandler(this.clicarBotao);
	}
}
